name: Fetch latest Hashnode blogs workflow
on:
 schedule: 
   - cron: '0 * * * *' 
 workflow_dispatch: 
jobs:
 update-readme-with-blog:
   name: Update this repo's README with latest blog posts
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: gautamkrishnar/blog-post-workflow@master
       with:
         comment_tag_name: "HASHNODE"
         feed_list: "https://ansumannn.hashnode.dev/rss.xml"
